####端口号
server:
  port: 80
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
spring:
  application:
    ####注册中心应用名称
    name: zuul-server
  cloud:
    config:
      profile: dev
      discovery:
        service-id: config-service
        enable: true

