###服务启动端口号
server:
  port: 8003
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-wanwh-xlzx
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka


    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
feign:
  hystrix:
    enabled: true

#### hystrix禁止服务超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000