eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wanweihua_1/springcloud2.0-config.git
          search-paths:
            - config
###共有仓库无需输入密码
#          username:
#          password:
      label: master
server:
  port: 8888
